### ISSUE TITLE
HTTPS redirecting is not working on Tools Labs

### ISSUE THREAD

**Issue by guilherme-pg** [guilherme-pg/citationhunt#21]
```
$ curl -v http://tools.wmflabs.org/citationhunt/
* Hostname was NOT found in DNS cache
*   Trying 208.80.155.131...
* Connected to tools.wmflabs.org (208.80.155.131) port 80 (#0)
> GET /citationhunt/ HTTP/1.1
> User-Agent: curl/7.37.1
> Host: tools.wmflabs.org
> Accept: */*
>
< HTTP/1.1 302 FOUND
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Date: Sun, 03 May 2015 20:50:54 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 283
< Connection: keep-alive
< Location: http://tools.wmflabs.org/citationhunt/?id=63836cf0&cat=all
< Cache-Control: no-cache, no-store
< X-Clacks-Overhead: GNU Terry Pratchett
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Connection #0 to host tools.wmflabs.org left intact
<p>You should be redirected automatically to target URL: <a href="/citationhunt/?id=63836cf0&amp;cat=all">/citationhunt/?id=63836cf0&amp;cat=all</a>.
```

**Comment by ricordisamoa** [comment]
Honestly, I fail to see why users should be forced to HTTPS.
Is there any private information which I'm not aware of?

**Comment by guilherme-pg** [comment]
There's no private information involved, but redirecting to HTTPS adds very little complexity to the code, and we get the guarantees of confidentiality and integrity for all users (the latter being arguably more important in this case).
I do realize that applying TLS to non-confidential assets is [contentious](https://news.ycombinator.com/item?id=9472867), but I personally think we should default to using HTTPS for all of our assets, unless we have a compelling reason not to. I'm fine with revisiting this decision in the future if it causes problems.

**Comment by ricordisamoa** [comment]
Unless I'm mistaken, every tool gets now redirected to HTTPS.
Maybe Tool Labs admins know something about that?

**Comment by guilherme-pg** [comment]
Hmm, I quickly tested this by commenting out the [section of the code](https://github.com/guilherme-pg/citationhunt/blob/da8375a5b51902ed5e6b41bc3d3fcf85b689e687/app.py#L109,L111) that sets up the redirection, and the redirection didn't happen automatically. Was this announced anywhere?

**Comment by ricordisamoa** [comment]
When I GET http://tools.wmflabs.org/ricordisamoa/ in Chromium, a `307 Internal Redirect` status is returned with headers `Location:https://tools.wmflabs.org/ricordisamoa/` and `Non-Authoritative-Reason:HSTS`.
Oddly, this doesn't seem to be the case with Firefox.
@yuvipanda: ?
